pluginManagement {
    repositories {
        maven { url 'file:/workspace/local-maven-repo' }
        google()
        mavenCentral()
    }
}

buildscript {
    repositories {
        maven { url 'file:/workspace/local-maven-repo' }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
    }
}

allprojects {
    repositories {
        maven { url 'file:/workspace/local-maven-repo' }
        google()
        mavenCentral()
    }
}

rootProject.name = "AICompiler"
include ':app'
