import React, { useState, useRef } from 'react';
import { useAppStore } from '../store/appStore';
import {
  FiPackage, FiPlay, FiDownload, FiCheckCircle,
  FiCpu, FiAlertCircle, FiLoader,
  FiSmartphone, FiFile, FiShield,
  FiUpload
} from 'react-icons/fi';
import toast from 'react-hot-toast';

interface BuildHistory {
  id: string;
  version: string;
  platform: 'android' | 'ios';
  buildType: 'debug' | 'release';
  timestamp: Date;
  status: 'success' | 'failed' | 'building';
  size?: string;
  apkPath?: string;
}

interface BuildPanelProps {
  isMobile?: boolean;
}

const BuildPanel: React.FC<BuildPanelProps> = ({ isMobile = false }) => {
  const { buildConfig, updateBuildConfig, selectedKey } = useAppStore();
  const [building, setBuilding] = useState(false);
  const [buildProgress, setBuildProgress] = useState(0);
  const [buildStatus, setBuildStatus] = useState('');
  const [buildHistory, setBuildHistory] = useState<BuildHistory[]>([]);
  const [exportingBuild, setExportingBuild] = useState<BuildHistory | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const generateSampleAPK = async (config: any): Promise<Blob> => {
    const { appName, appId, version, versionCode, buildType } = config;
    const date = new Date().toISOString();

    const apkMetadata = `
APK Manifest:
=============
Package: ${appId}
Version: ${version} (${versionCode})
Name: ${appName}
Type: ${buildType}
Date: ${date}
Generated by: AI Compiler
=============================================
`;

    const content = apkMetadata + generateDummyAPKContent();
    const blob = new Blob([content], { type: 'application/vnd.android.package-archive' });
    return blob;
  };

  const generateDummyAPKContent = (): string => {
    return `
# APK File Structure (Simulated)
├── AndroidManifest.xml
├── classes.dex
├── resources.arsc
├── META-INF/
│   ├── MANIFEST.MF
│   ├── CERT.SF
│   └── CERT.RSA
├── res/
│   ├── drawable/
│   ├── layout/
│   └── values/
└── assets/
    └── index.html

# File Contents Summary (Simulated)

## AndroidManifest.xml
<manifest package="${buildConfig.appId}" versionCode="${buildConfig.versionCode}" versionName="${buildConfig.version}">
  <application label="${buildConfig.appName}" theme="@style/AppTheme"/>
</manifest>

## classes.dex (compiled bytecode)
Lcom/aicompiler/app/MainActivity;
Lcom/aicompiler/app/AICore;

## resources.arsc (resource table)
string/app_name="${buildConfig.appName}"

## Build Info
Built at: ${new Date().toISOString()}
Build ID: ${Math.random().toString(36).substring(7)}
Architecture: universal
Min SDK: 22
Target SDK: 34
    `.trim();
  };

  const downloadFile = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const saveToDesktop = async (build: BuildHistory) => {
    setExportingBuild(build);
    try {
      const apkBlob = await generateSampleAPK(buildConfig);
      const filename = `${buildConfig.appName}-v${build.version}-${build.buildType}.apk`;
      downloadFile(apkBlob, filename);
      toast.success(`APK 已下载到本地: ${filename}`);
    } catch (error) {
      toast.error('APK 下载失败');
    } finally {
      setExportingBuild(null);
    }
  };

  const handleBuild = async () => {
    if (!selectedKey) {
      toast.error('请先在"签名密钥"页面创建并选择签名密钥');
      return;
    }

    setBuilding(true);
    setBuildProgress(0);

    const newBuild: BuildHistory = {
      id: Date.now().toString(),
      version: buildConfig.version,
      platform: 'android',
      buildType: buildConfig.buildType,
      timestamp: new Date(),
      status: 'building'
    };

    setBuildHistory([newBuild, ...buildHistory]);

    const buildSteps = [
      { progress: 10, status: '正在清理旧构建文件...' },
      { progress: 25, status: '正在编译资源文件...' },
      { progress: 40, status: '正在编译 TypeScript 代码...' },
      { progress: 55, status: '正在打包 JavaScript bundle...' },
      { progress: 65, status: '正在生成 Android 项目...' },
      { progress: 75, status: '正在编译 DEX 文件...' },
      { progress: 85, status: '正在签名 APK...' },
      { progress: 95, status: '正在优化 APK...' },
      { progress: 100, status: '构建完成!' }
    ];

    for (const step of buildSteps) {
      await new Promise(resolve => setTimeout(resolve, 600));
      setBuildProgress(step.progress);
      setBuildStatus(step.status);
    }

    const buildSize = buildConfig.buildType === 'release'
      ? `${(10 + Math.random() * 15).toFixed(1)} MB`
      : `${(20 + Math.random() * 20).toFixed(1)} MB`;

    setBuildHistory((history) =>
      history.map((h) =>
        h.id === newBuild.id
          ? { ...h, status: 'success', size: buildSize, apkPath: `/release/${buildConfig.appName}.apk` }
          : h
      )
    );

    const buildInfo = {
      appName: buildConfig.appName,
      appId: buildConfig.appId,
      version: buildConfig.version,
      versionCode: buildConfig.versionCode,
      buildType: buildConfig.buildType,
      platform: 'android',
      minSdk: 22,
      targetSdk: 34,
      signed: true,
      signingKey: {
        alias: selectedKey.alias,
        algorithm: selectedKey.algorithm,
        keySize: selectedKey.keySize
      },
      buildTime: new Date().toISOString(),
      buildSize
    };

    const blob = new Blob([JSON.stringify(buildInfo, null, 2)], { type: 'application/json' });
    downloadFile(blob, `${buildConfig.appName}-v${buildConfig.version}-build-info.json`);

    toast.success(`🎉 构建成功! APK 大小: ${buildSize}`);
    setBuilding(false);
    setBuildStatus('');
  };

  const handleExportConfig = () => {
    const config = {
      appName: buildConfig.appName,
      appId: buildConfig.appId,
      version: buildConfig.version,
      versionCode: buildConfig.versionCode,
      buildType: buildConfig.buildType,
      platform: 'android',
      signingKey: selectedKey ? {
        alias: selectedKey.alias,
        algorithm: selectedKey.algorithm,
        keySize: selectedKey.keySize,
        validUntil: selectedKey.validUntil
      } : null
    };

    const blob = new Blob([JSON.stringify(config, null, 2)], { type: 'application/json' });
    downloadFile(blob, `${buildConfig.appName}-build-config.json`);
    toast.success('构建配置已导出');
  };

  const handleFileSelect = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      toast.success(`已选择文件: ${file.name}`);
    }
  };

  return (
    <div className={`h-full overflow-y-auto scrollbar-thin ${isMobile ? 'p-4' : ''}`}>
      <div className={`${isMobile ? '' : 'max-w-6xl mx-auto p-8'}`}>
        <div className="mb-6">
          <h1 className={`font-bold flex items-center space-x-3 ${isMobile ? 'text-lg' : 'text-2xl'}`}>
            <FiPackage className="text-ai-cyan" />
            <span>应用打包与构建</span>
          </h1>
          <p className="text-gray-400 mt-2 text-sm">
            配置应用信息并打包为 Android 原生安装包 (APK)
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
          <div className="lg:col-span-2 gradient-border p-6 rounded-xl">
            <h2 className="text-lg font-semibold mb-4 flex items-center space-x-2">
              <FiCpu size={20} />
              <span>构建配置</span>
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  应用名称
                </label>
                <input
                  type="text"
                  value={buildConfig.appName}
                  onChange={(e) => updateBuildConfig({ appName: e.target.value })}
                  className="w-full px-4 py-2 bg-slate-700 rounded-lg border border-slate-600 focus:border-primary-500 focus:outline-none text-white"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  应用包名
                </label>
                <input
                  type="text"
                  value={buildConfig.appId}
                  onChange={(e) => updateBuildConfig({ appId: e.target.value })}
                  className="w-full px-4 py-2 bg-slate-700 rounded-lg border border-slate-600 focus:border-primary-500 focus:outline-none text-white font-mono"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  版本号 (SemVer)
                </label>
                <input
                  type="text"
                  value={buildConfig.version}
                  onChange={(e) => updateBuildConfig({ version: e.target.value })}
                  placeholder="1.0.0"
                  className="w-full px-4 py-2 bg-slate-700 rounded-lg border border-slate-600 focus:border-primary-500 focus:outline-none text-white font-mono"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  版本代码
                </label>
                <input
                  type="number"
                  value={buildConfig.versionCode}
                  onChange={(e) => updateBuildConfig({ versionCode: parseInt(e.target.value) })}
                  min="1"
                  className="w-full px-4 py-2 bg-slate-700 rounded-lg border border-slate-600 focus:border-primary-500 focus:outline-none text-white"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  构建类型
                </label>
                <select
                  value={buildConfig.buildType}
                  onChange={(e) => updateBuildConfig({ buildType: e.target.value as 'debug' | 'release' })}
                  className="w-full px-4 py-2 bg-slate-700 rounded-lg border border-slate-600 focus:border-primary-500 focus:outline-none text-white"
                >
                  <option value="debug">Debug (调试版)</option>
                  <option value="release">Release (发布版)</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  目标平台
                </label>
                <select
                  value={buildConfig.platform}
                  onChange={(e) => updateBuildConfig({ platform: e.target.value as 'android' | 'ios' | 'all' })}
                  className="w-full px-4 py-2 bg-slate-700 rounded-lg border border-slate-600 focus:border-primary-500 focus:outline-none text-white"
                >
                  <option value="android">Android (APK)</option>
                  <option value="ios">iOS (IPA)</option>
                  <option value="all">全部平台</option>
                </select>
              </div>
            </div>

            {!selectedKey ? (
              <div className="mt-4 p-3 bg-yellow-500/10 border border-yellow-500/30 rounded-lg flex items-start space-x-2">
                <FiAlertCircle className="text-yellow-500 mt-0.5" />
                <div>
                  <p className="text-sm text-yellow-200">签名密钥未配置</p>
                  <p className="text-xs text-yellow-300 mt-1">
                    请在"签名密钥"页面创建并选择一个密钥
                  </p>
                </div>
              </div>
            ) : (
              <div className="mt-4 p-3 bg-green-500/10 border border-green-500/30 rounded-lg flex items-start space-x-2">
                <FiShield className="text-green-500 mt-0.5" />
                <div>
                  <p className="text-sm text-green-200">签名密钥已配置</p>
                  <p className="text-xs text-green-300 mt-1">
                    使用 "{selectedKey.alias}" 密钥签名
                  </p>
                </div>
              </div>
            )}
          </div>

          <div className="gradient-border p-6 rounded-xl">
            <h2 className="text-lg font-semibold mb-4">快速操作</h2>

            {building && (
              <div className="mb-4">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-gray-400">构建进度</span>
                  <span className="text-sm font-mono text-primary-400">{Math.round(buildProgress)}%</span>
                </div>
                <div className="h-2 bg-slate-700 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-primary-600 to-ai-cyan transition-all duration-300"
                    style={{ width: `${buildProgress}%` }}
                  />
                </div>
                <p className="text-xs text-gray-500 mt-2">{buildStatus}</p>
              </div>
            )}

            <div className="space-y-3">
              <button
                onClick={handleBuild}
                disabled={building || !selectedKey}
                className="w-full py-3 bg-gradient-to-r from-primary-600 to-ai-purple rounded-lg font-medium hover:opacity-90 transition-opacity disabled:opacity-50 flex items-center justify-center space-x-2"
              >
                {building ? (
                  <>
                    <FiLoader className="animate-spin" size={18} />
                    <span>构建中...</span>
                  </>
                ) : (
                  <>
                    <FiPlay size={18} />
                    <span>开始构建 APK</span>
                  </>
                )}
              </button>

              <button
                onClick={handleExportConfig}
                disabled={building}
                className="w-full py-3 bg-slate-700 hover:bg-slate-600 rounded-lg font-medium transition-colors flex items-center justify-center space-x-2 disabled:opacity-50"
              >
                <FiDownload size={18} />
                <span>导出配置</span>
              </button>

              <button
                onClick={handleFileSelect}
                className="w-full py-3 bg-slate-700/50 hover:bg-slate-700 rounded-lg font-medium transition-colors flex items-center justify-center space-x-2 border border-dashed border-slate-600"
              >
                <FiUpload size={18} />
                <span>上传文件</span>
              </button>
              <input
                ref={fileInputRef}
                type="file"
                className="hidden"
                onChange={handleFileChange}
              />
            </div>

            <div className="mt-6 p-4 bg-slate-700/50 rounded-lg">
              <h3 className="text-sm font-semibold mb-3 flex items-center space-x-2">
                <FiSmartphone size={16} />
                <span>构建预览</span>
              </h3>
              <div className="space-y-2 text-xs text-gray-400">
                <div className="flex justify-between">
                  <span>输出格式:</span>
                  <span className="font-mono text-ai-cyan">APK</span>
                </div>
                <div className="flex justify-between">
                  <span>签名算法:</span>
                  <span className="font-mono">{selectedKey?.algorithm || 'N/A'}</span>
                </div>
                <div className="flex justify-between">
                  <span>密钥长度:</span>
                  <span className="font-mono">{selectedKey?.keySize ? `${selectedKey.keySize}-bit` : 'N/A'}</span>
                </div>
                <div className="flex justify-between">
                  <span>优化级别:</span>
                  <span className="font-mono">{buildConfig.buildType === 'release' ? 'O2' : 'O0'}</span>
                </div>
                <div className="flex justify-between">
                  <span>最小 SDK:</span>
                  <span className="font-mono">API 22</span>
                </div>
                <div className="flex justify-between">
                  <span>目标 SDK:</span>
                  <span className="font-mono">API 34</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="gradient-border p-6 rounded-xl">
          <h2 className="text-lg font-semibold mb-4 flex items-center space-x-2">
            <FiFile size={20} />
            <span>构建历史</span>
          </h2>

          {buildHistory.length === 0 ? (
            <div className="text-center py-12">
              <FiPackage size={48} className="mx-auto mb-3 text-gray-600" />
              <p className="text-gray-400">暂无构建记录</p>
              <p className="text-sm text-gray-500 mt-1">完成构建后将显示在这里</p>
            </div>
          ) : (
            <div className="space-y-3">
              {buildHistory.map((build) => (
                <div
                  key={build.id}
                  className="flex items-center justify-between p-4 bg-slate-700/30 rounded-lg"
                >
                  <div className="flex items-center space-x-4">
                    <div className={`p-2 rounded-lg ${
                      build.status === 'success' ? 'bg-green-500/20' :
                      build.status === 'building' ? 'bg-blue-500/20' :
                      'bg-red-500/20'
                    }`}>
                      {build.status === 'success' ? (
                        <FiCheckCircle className="text-green-400" size={20} />
                      ) : build.status === 'building' ? (
                        <FiLoader className="text-blue-400 animate-spin" size={20} />
                      ) : (
                        <FiAlertCircle className="text-red-400" size={20} />
                      )}
                    </div>

                    <div>
                      <p className="font-medium">
                        {buildConfig.appName} v{build.version} ({build.buildType})
                      </p>
                      <p className="text-sm text-gray-400">
                        Android • {build.timestamp.toLocaleString()}
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center space-x-4">
                    {build.size && (
                      <span className="text-sm text-gray-400">{build.size}</span>
                    )}
                    <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                      build.status === 'success' ? 'bg-green-500/20 text-green-400' :
                      build.status === 'building' ? 'bg-blue-500/20 text-blue-400' :
                      'bg-red-500/20 text-red-400'
                    }`}>
                      {build.status === 'success' ? '成功' :
                       build.status === 'building' ? '构建中' : '失败'}
                    </span>
                    {build.status === 'success' && (
                      <button
                        onClick={() => saveToDesktop(build)}
                        disabled={exportingBuild?.id === build.id}
                        className="p-2 hover:bg-slate-600 rounded-lg transition-colors disabled:opacity-50 flex items-center space-x-1"
                        title="下载 APK"
                      >
                        {exportingBuild?.id === build.id ? (
                          <FiLoader className="animate-spin" size={18} />
                        ) : (
                          <FiDownload size={18} />
                        )}
                        <span className="text-xs">下载</span>
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default BuildPanel;
